### PR TITLE
Remove data-uri encoding of woff font.

### PR DESCRIPTION
**Pull request by tollmanz**
In researching WordPress' Twentyfifteen theme performance, I found that
data-uri enconding the woff Genericons font file could cause visually
complete delays of up to 300ms on a mobile connection.

When a browser tries to render a page, it tries to complete the CSSOM as
quickly as possible so the first paint can be completed. The CSSOM is
dependent upon the CSS being downloaded from the server(s). Any delays
in getting the CSS can cause delays in rendering the page.

The Genericons CSS files weighs in around 16k and can be reduced to 2k
with the encoded woff file removed. The size reduction is significant
and can lead to much quicker resolution of the CSSOM if this change is
made.

Furthermore, data-uri encoding the font into the CSS requires that all
browsers receive the font even if it cannot be used by the browser. If
all fonts are located at external locations, the browser can make the
decision about which ones to load instead of the application, which is
not in a good place to make such a decision.

This commit removes the data-uri encoded font and prefers the external
font file instead.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for the pull request. 

I'm not convinced it should be merged into Genericons proper though. Also, while TwentyFifteen could theoretically use a modified version of the CSS, I'm not even sure that's a good idea.

I'm not personally thrilled to have the base64 version included, there's no argument that it adds extra weight to the download. But it was a trade-off between ease of use and load-time.

The problem with not including base64 is that fonts will break if a user uses a static CDN for the font files. This is common in loads of caching plugins. All the nitty gritty details are in this post: http://davidwalsh.name/cdn-fonts -- but the short of it is, unless the font is served from the same domain as the one it's used on, the font won't load in modern browsers at all. The proper way to fix this is to add access control headers to the htaccess files or apache configuration, but base64 encoding it is a hack that circumvents this. 

So by including the base64 hack, we ensure that casual users can download a theme that uses stock Genericons and it'll just work with their setup. If we did not include base64 -- like we did in the beginning -- we'll see tons of users confused why their icons aren't working.

An alternative solution would be to provide two CSS files in the Genericons download package, the default `genericons.css` and for the pro-users a `genericons-lite.css` (or a better name), then explain in the readme file why you might want to enqueue the latter. It would be an extra 16K of disk space used on the server (unless you delete the file you won't be using), but only the file enqueued will actually be loaded.

Thoughts?

**Comment by tollmanz** [comment]
Thanks for taking to time to explain the history behind this decision @jasmussen.

I understand where you are coming from with your decision to encode the font. I disagree with the approach as it is shipping a "hack" as the default setup for the font. The "casual user" is likely not the same user that uses the fonts with a CDN, but this is tough to quantify. It's just hard to agree with a compromised default experience that is optimized for the potential that a novice user will be using a system that allows them to deploy a website with CDN integration. It would seem better to deploy this project with best practices and other projects that use it can integrates workarounds for improved user experience.

If the woff file is being encoded, why aren't the other fonts being encoded as well? Wouldn't users end up with the same issue if the browser choses to use one of the other fonts?

> If we did not include base64 -- like we did in the beginning -- we'll see tons of users confused why their icons aren't working.

To be clear, this change was in response to user reports? Was this for WordPress themes using it or with other projects?

> An alternative solution would be to provide two CSS files in the Genericons download package, the default genericons.css and for the pro-users a genericons-lite.css (or a better name), then explain in the readme file why you might want to enqueue the latter. It would be an extra 16K of disk space used on the server (unless you delete the file you won't be using), but only the file enqueued will actually be loaded.

As you probably can imagine, I'd like to see the non-encoded version be the default with a "compat" version as a secondary version.

My main beef with this is that encoded fonts are really problematic. CSSOM construction is so important for a browser being able to get to the first paint. Extra bytes in CSS are a major culprit in blocking the CSSOM construction. When you add fonts to the CSS, you run the risk of not even needing the font in the first place. The current page might not use the font or a different font type my be preferred for the browser. As such, loading fonts via an external source tends to be the best option for performance. In the case of an icon font, loading the font in the CSS essentially prioritizes non-textual (i.e., design) elements over loading the important site content.

I appreciate you elaborating on the decision to encode the font. It is reasonable and makes sense. I personally would love to see a project like this push for better performance practices even though it may mean compatibility issues.

**Comment by jasmussen** [comment]
>  The "casual user" is likely not the same user that uses the fonts with a CDN, but this is tough to quantify. It's just hard to agree with a compromised default experience that is optimized for the potential that a novice user will be using a system that allows them to deploy a website with CDN integration. It would seem better to deploy this project with best practices and other projects that use it can integrates workarounds for improved user experience.

I can't fault anything you say, and I don't have any desire to do so either. Using base64 encoding *is* a hack, there's no getting around that.

Also keep in mind here that I think it makes perfect sense to ship a second version without the base64 stuff, and updating the readme to explain what it's all about. We're discussing defaults here: should the base experience be "plug and play" for the majority of users but with a performance hit, or should we be forward looking and require a little effort from the user?

The fact that we're shipping a hack by default doesn't worry me too much. As webdesigners we've had to do this for years for IE. In fact I'd argue that icon fonts are a giant unsemantic hack already. Not only are icon fonts [ruining your markup](http://noscope.com/2014/icon-fonts-are-ruining-your-markup/), but indeed you're loading *every* icon included in the font, even those you aren't using in a design.

Icon fonts solve a real problem today, and their biggest strength is how compatible they are across browsers. While I can see a very good reason to ship the second CSS file, I would still argue in favor of keeping the defaults as compatible as possible.

> If the woff file is being encoded, why aren't the other fonts being encoded as well? Wouldn't users end up with the same issue if the browser choses to use one of the other fonts?

WOFF is the most modern font standard, supported by all the modern browsers. TTF is for older IEs, EOT is for VERY old IEs and SVG is for old versions of iOS. In fact EOT and SVG can probably soon be retired, but since they aren't loaded unless used I've seen no reason to optimize that aspect.

Incidentally, the browsers that are so old as to use SVG, EOT or TTF they don't block cross origin font requests. Only modern browsers, which would request the WOFF file, block these requests.

The syntax to serve specific font types to specific browsers, by the way, is in itself a rather elaborate and clever hack, called [The Bulletproof Font Face Syntax](http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/). 

> To be clear, this change was in response to user reports? Was this for WordPress themes using it or with other projects?

This was through internal testing and reports internally at Automattic and via WordPress.com, as this was before development of Genericons had been moved to Github.

**Comment by tollmanz** [comment]
> Yes, this was through internal testing and reports internally at Automattic and via WordPress.com, as this was before development of Genericons had been moved to Github.

This is a great way to conclude your response. If this is a *real* problem backed with data, I do not see a reason to change it now. It's a bummer, but fortunately, the encoding font is relatively small.

Thanks for indulging me and taking the time to explain the decisions that went into this change. I really appreciate it.

**Comment by jasmussen** [comment]
> Thanks for indulging me and taking the time to explain the decisions that went into this change. I really appreciate it.

Thank you for wanting to make Genericons better.

I think there could still be a good reason to bundle an extra CSS file with the download, that did not include the base64 version.

**Pull request closed without merging**
