### PR TITLE
New Genericons

### PR DESCRIPTION
**Pull request by jasmussen**
This PR contains a complete refactor of the codebase that builds Genericons. 
- It moves the process to Node and Grunt, making it faster and easier to build and contribute. 
- It moves to prioritize SVG over icon-fonts, and provides multiple ways to use the SVGs (sprites, PHP functions, individual minimized SVGs)
- It removes all logos, and renews focus on being just an icon set. If you need logos, there are [better alternatives anyway](https://github.com/Automattic/social-logos)

genericons

The new genericons comes with multiple options you can use for your projects:
- Plain minified SVGs (in the `svg-min` folder).
- An SVG-sprite that uses use to have inline SVG graphics but still an external file (in the `svg-sprite` folder)
- PHP files containing SVG in either inline or sprite versions (in the `svg-php` folder) — thanks for that Sarah!
- An icon font for plan B situations (in the `icon-font` folder)

**No logos?** Because Genericons was so early to the icon-font game, it more or less became a kitchen-sink for icons containing all sorts of one-offs and logos. To slim things down, renew focus, all logos and a few edge-case icons have been removed. In the absence of logos in Genericons, there's [Social Logos](https://github.com/Automattic/social-logos), which is a great and up-to-date set of logos.
## Please use it today!

I'm taking a break from computers, but didn't want to leave this branch unseen, as it's pretty much ready to go. So feel free to start using the new Genericons today through this branch, and pretty please do leave your feedback here. If all goes well I'll merge it into master when I get back, hopefully with few to no changes at all. Consider this a beta test, and let me know your thoughts!

### CODE REVIEW

**Comment by MichaelArestad** [comment]
This makes me happy. Thank you.

**Comment by Ipstenu** [comment]
First pass at Genericon'd (the plugin) using these is up!

https://github.com/Ipstenu/genericond/tree/REL_4.0.0

It's actually not terribly hard to convert the plugin, though I had to fork your genericons.php stuff so it didn't point to themes and so I could insert extra stuff I use. I just need to clean up the example page really now 🍡

**Comment by jasmussen** [comment]
You're the best, Mika!

**Comment by justintadlock** [comment]
I'll be honest, I'm a little disappointed that logo icons are being removed.  It'll definitely create some back-compatibility concerns for child themes users if I update my themes.  I know there's a handful of them that are using custom CSS to do some neat stuff.

I'll have to look into using the Automattic social icons. ;)

**Comment by Ipstenu** [comment]
The only real issue with including Social Logos is you chuffers have different default pixel sizes, which sucks and made for some weird code.

**Comment by georgestephanis** [comment]
Honestly, I agree with @justintadlock -- removing icons breaks backward compatability -- so I worry about any plugins or themes that had been relying on the social icons in Genericons, only to get upgraded (either by dev choice, or the Genericon'd or Jetpack plugin updates it for them) and suddenly the icons no longer show, generating headaches and support requests.

I'd be fine with removing documentation of the logos being in the font, but please silently leave them in for backwards compat.

**Comment by Ipstenu** [comment]
The font-packs are still included actually, and I've added in an option in Genericon'd to turn them on if needed (which can easily be done). 

Also I included both social AND Genericons. So ... being aware of the situation means I can cause the least amount of impact to my users. I don't worry about this. If a theme/plugin is including Genericons and doesn't read the changelogs, well that's _always_ been an issue with libraries, now, hasn't it?

I see it as a mild annoyance, but Jetpack can just pull in social logos too, as a font if you need it, as both libraries are including legacy fonts.

**Comment by dshanske** [comment]
Isn't the answer to problems with the Automattic Social Icons making changes there to better accommodate conversion as well? Personally, I am fine with the division. Already used it as an excuse to switch to SVG

**Comment by jasmussen** [comment]
Glad we let this PR sit for a bit, to gather feedback.

@justintadlock 

> I'll be honest, I'm a little disappointed that logo icons are being removed. It'll definitely create some back-compatibility concerns for child themes users if I update my themes. I know there's a handful of them that are using custom CSS to do some neat stuff.

@georgestephanis 

> I worry about any plugins or themes that had been relying on the social icons in Genericons, only to get upgraded (either by dev choice, or the Genericon'd or Jetpack plugin updates it for them) and suddenly the icons no longer show, generating headaches and support requests.

These are legitimate concerns. 

So far my thought process has been: *just don't upgrade*. But I failed to take into account packages that bundle genericons for others to use, such as child themes. 

I think it's important to keep the eye on the ball here — the purpose of this PR is to re-invigorate Genericons, breathe life into it, move it forward. I see the removal of social icons as a critical part of that. It removes a reduncancy that is both served better by other offerings, and it removes what has turned out to be the single biggest workload for the entire set. It was never the purpose of Genericons to be a kitchen sink of logos, and with so few contributors it's never fun to be the arbiter of which logos go in and which don't. 

I've thought of ways to alleviate this; change the font name itself, for example, to "Genericons Neue", and include the old font file for back-compat. But then I spoke to George in person just a little while ago, asked him what he thought was the best approach. He thought the best thing to do would be not only a new name, but a new repository as well. 

I'm personally okay with a new name + new repo, my main concern is that it would essentially mean abandoning this repo entirely, letting it just sit there unloved.

I'd love your thoughts on this — is there another path forward that maintains back-compat while not abandoning this repo?

**Comment by jasmussen** [comment]
As a quick follow-up, in the event of deciding to split to new name + new repo, I could back-port the move to `npm` for the build process, so the old repo could at least have an easier build process for people who wanted to contribute to that.

**Comment by celloexpressions** [comment]
I think a new name will be necessary, since removing or renaming any icons would cause back-compat problems for all of the themes and plugins that bundle it. Because they (in theory) would be using `wp_enqueue_style`, some other plugin loading a the new version could cause breakage to a theme if the plugin's version is loaded instead. Renaming would give full freedom for refreshing everything without back-compat issues.

In terms of a new repo... I could see both versions coexisting in the same repo potentially, in separate folders.

**Comment by jasmussen** [comment]
> I think a new name will be necessary, since removing or renaming any icons would cause back-compat problems for all of the themes and plugins that bundle it

> I could see both versions coexisting in the same repo potentially, in separate folders.

I could get on board with this. Any further thoughts?

**Comment by MichaelArestad** [comment]
@jasmussen Specificons

**Comment by jasmussen** [comment]
@michaelarestad I like it, but I like Genericons Neue more ;)

**Comment by jasmussen** [comment]
The new Genericons has a new name, Genericons Neue, and a new repository: https://github.com/Automattic/genericons-neue

🎉 

Closing this branch for now, and will probably update the readme to reflect this.

**Pull request closed without merging**
